/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_lpspi.h"
#include "fsl_lpi2c.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for LPSPI3 */
/* Definition of peripheral ID */
#define LPSPI3_PERIPHERAL LPSPI3
/* Definition of clock source */
#define LPSPI3_CLOCK_FREQ 105600000UL
/* LPSPI3 interrupt vector ID (number). */
#define LPSPI3_IRQN LPSPI3_IRQn
/* LPSPI3 interrupt handler identifier. */
#define LPSPI3_IRQHANDLER LPSPI3_IRQHandler
/* BOARD_InitPeripherals defines for LPI2C1 */
/* Definition of peripheral ID */
#define LPI2C1_PERIPHERAL LPI2C1
/* Definition of clock source */
#define LPI2C1_CLOCK_FREQ 60000000UL
/* Definition of follower address */
#define LPI2C1_MASTER_SLAVE_ADDRESS 0
/* LPI2C1 interrupt vector ID (number). */
#define LPI2C1_IRQN LPI2C1_IRQn
/* LPI2C1 interrupt handler identifier. */
#define LPI2C1_IRQHANDLER LPI2C1_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpspi_master_config_t LPSPI3_config;
extern const lpi2c_master_config_t LPI2C1_masterConfig;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
